[tools]
air = "latest"
antigravity-cli = "latest"
bun = "latest"
cloudflared = "latest"
codex = "latest"
deno = "latest"
"gem:zsteg" = "latest"
htmlq = "latest"
lazydocker = "latest"
lazygit = "latest"
"npm:@playwright/cli" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:playwright" = "latest"
opencode = "latest"
starship = "latest"
watchexec = "latest"
yazi = "latest"
