[tools]
actionlint = "latest"
air = "latest"
antigravity-cli = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
biome = "latest"
bun = "latest"
cloudflared = "latest"
codex = "latest"
deno = "latest"
gcloud = "latest"
"gem:zsteg" = "latest"
htmlq = "latest"
lazydocker = "latest"
lazygit = "latest"
"npm:@playwright/cli" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:playwright" = "latest"
opencode = "latest"
prettier = "latest"
starship = "latest"
watchexec = "latest"
yazi = "latest"
