#!/usr/bin/env zsh

fzf_to_project() {
  local -a search_paths fzf_result
  local action selected

  search_paths=(~/dev ~)
  fzf_result=("${(@f)$(
    {
      echo "$HOME"
      echo "$HOME/.local/share/applications"
      find -L "${search_paths[@]}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null
      find "$HOME/Documents" \( -name "node_modules" -o -name ".venv" -o -name ".git" \) -prune -o -type d 2>/dev/null
    } | sed "s|^$HOME|~|" | fzf \
      --expect=ctrl-e,ctrl-o,ctrl-t \
      --header "Enter: cd/open session | Ctrl-E: Neovim | Ctrl-O: xdg-open" \
      --scheme=path
  )}")

  action="$fzf_result[1]"
  selected=$(echo "$fzf_result[2]" | sed "s|^~|$HOME|")

  if [[ -z $selected ]]; then
    echo "Nothing selected, exiting"
    return
  fi

  case "$action" in
  ctrl-e)
    nvim "$selected"
    ;;
  ctrl-o)
    xdg-open "$selected" >/dev/null 2>&1 &|
    ;;
  *)
    cd "$selected"
    ;;
  esac
}

transcribe() {
  local filename="$1"
  local model_path="$HOME/dev/whisper.cpp/models/ggml-${2:-"medium.en"}.bin"

  if [[ -z "$filename" ]]; then
    echo "Error: The first argument is required."
    echo "Usage: transcribe <filename> [model, default: medium.en]"
    return 1
  fi

  ffmpeg -i "$filename" -f wav -ar 16000 -ac 1 -c:a pcm_s16le - |
    whisper-cli \
      -m "$model_path" \
      -t 6 \
      --print-progress \
      -osrt \
      -f - \
      --output-file "$(basename "$filename")"
}

# ALIASES
alias vim='nvim'
alias gs='git status'
alias ls='ls --color=auto --hyperlink=auto -p -h'
alias f='fzf_to_project'
alias c='wl-copy'
alias p='wl-paste'
alias o='xdg-open'

# KEYBINDINGS
bindkey -e
# Move through history with the same prefix
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward
# Edit command
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# HISTORY
HISTSIZE=1000000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt INTERACTIVECOMMENTS

setopt AUTO_PUSHD

setopt EXTENDED_GLOB

if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

# FZF
# Set up fzf key bindings and fuzzy completion
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh)
fi

# Enable completions
fpath=(
  /opt/homebrew/share/zsh/site-functions
  /usr/share/zsh/site-functions
  /usr/local/share/zsh/site-functions
  $fpath
)
autoload -Uz compinit
compinit

if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

# PLUGINS
ZPLUGINDIR=${XDG_DATA_HOME:-$HOME/.local/share}/zsh-plugins
mkdir -p $ZPLUGINDIR

# zsh-autosuggestions
if [[ ! -d $ZPLUGINDIR/zsh-autosuggestions ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions \
    $ZPLUGINDIR/zsh-autosuggestions
fi
source $ZPLUGINDIR/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

# zsh-syntax-highlighting
if [[ ! -d $ZPLUGINDIR/zsh-syntax-highlighting ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting \
    $ZPLUGINDIR/zsh-syntax-highlighting
fi
source $ZPLUGINDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# Set Bitwarden as SSH agent if exists
BITWARDEN_MACOS="$HOME/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock"
BITWARDEN_FLATPAK="$HOME/.var/app/com.bitwarden.desktop/.bitwarden-ssh-agent.sock"
if [[ -S "$BITWARDEN_FLATPAK" ]]; then
  # use the flatpak version
  export SSH_AUTH_SOCK="$BITWARDEN_FLATPAK"
elif [[ -S "$BITWARDEN_MACOS" ]]; then
  export SSH_AUTH_SOCK="$BITWARDEN_MACOS"
fi

# turn on starship prompt if installed
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
