#!/usr/bin/env zsh

# Load secrets
[ -f ~/.secrets ] && source ~/.secrets

fzf_to_project() {
  local -a search_paths fzf_result
  local action selected

  search_paths=(~/dev ~)
  fzf_result=("${(@f)$(
    {
      echo "$HOME"
      echo "$HOME/.local/share/applications"
      find -L "${search_paths[@]}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null
      find "$HOME/Documents" \( -name "node_modules" -o -name ".venv" -o -name ".git" \) -prune -o -type d 2>/dev/null
    } | fzf \
      --expect=ctrl-e,ctrl-o,ctrl-t \
      --header "Enter: cd/open session | Ctrl-E: Neovim | Ctrl-O: xdg-open" \
      --scheme=path
  )}")

  action="$fzf_result[1]"
  selected="$fzf_result[2]"

  if [[ -z $selected ]]; then
    echo "Nothing selected, exiting"
    return
  fi

  case "$action" in
  ctrl-e)
    nvim "$selected"
    ;;
  ctrl-o)
    xdg-open "$selected" >/dev/null 2>&1 &|
    ;;
  *)
    cd "$selected"
    ;;
  esac
}

# ALIASES
alias vim='nvim'
alias gs='git status'
alias ls='ls --color=auto -p -h'
alias f='fzf_to_project'
alias c='wl-copy'
alias p='wl-paste'
alias o='xdg-open'

# KEYBINDINGS
bindkey -e
# Move through history with the same prefix
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward
# Edit command
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# HISTORY
HISTSIZE=1000000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

setopt AUTO_PUSHD

setopt EXTENDED_GLOB

if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

# FZF
# Set up fzf key bindings and fuzzy completion
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh)
fi

# Enable completions
fpath=(
  /opt/homebrew/share/zsh/site-functions
  /usr/share/zsh/site-functions
  /usr/local/share/zsh/site-functions
  $fpath
)
autoload -Uz compinit
compinit

if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

# PLUGINS
ZPLUGINDIR=${XDG_DATA_HOME:-$HOME/.local/share}/zsh-plugins
mkdir -p $ZPLUGINDIR

# zsh-autosuggestions
if [[ ! -d $ZPLUGINDIR/zsh-autosuggestions ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions \
    $ZPLUGINDIR/zsh-autosuggestions
fi
source $ZPLUGINDIR/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

# zsh-syntax-highlighting
if [[ ! -d $ZPLUGINDIR/zsh-syntax-highlighting ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting \
    $ZPLUGINDIR/zsh-syntax-highlighting
fi
source $ZPLUGINDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# Set Bitwarden as SSH agent
if [[ "$(uname)" == "Darwin" ]]; then
  export SSH_AUTH_SOCK="$HOME/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock"
else
  # assume linux
  # export SSH_AUTH_SOCK=$HOME/.bitwarden-ssh-agent.sock
  # use the flatpak version
  export SSH_AUTH_SOCK=/home/erykksc/.var/app/com.bitwarden.desktop/.bitwarden-ssh-agent.sock
fi

# turn on starship prompt if installed
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
