import = [
    "/Users/erykksc/.config/alacritty/themes/github_dark.toml",
]

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 1
blur = true
option_as_alt = "Both"

[font]
# normal.family = "JetBrainsMono Nerd Font"
normal.family = "ComicShannsMono Nerd Font Mono"
size=13
# normal.family = "OpenDyslexicM Nerd Font Mono"
# size=12

[shell]
program = "zsh"
args = ["-il", "-c", "/Users/erykksc/.dotfiles/scripts/tmux-client.sh"]
