import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 1
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size=12

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "general"]
