import = [
    "/Users/erykksc/.config/alacritty/themes/themes/github_light.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 1
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size=12

[shell]
program = "zsh"
args = ["-il", "-c", "/Users/erykksc/.dotfiles/scripts/tmux-client.sh"]
