import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 1
blur = false

[font]
normal.family = "Hack Nerd Font"

size=12
